sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: hjb20040116
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tJgWSpVZLiMycMzyjBz
    access-key-secret: CjFeh5Hlu1LBmlhEZUF23ObfPSjaqB
    bucket-name: web-sky-take-out-test
  redis:
    host: localhost
    port: 6379
    #password: hjb20040116
    #database: 10